### ISSUE TITLE
Support platform-independent directory separators in installation paths

### ISSUE THREAD

**Issue by podcherklife** [dark0dave/mod_installer#21]
I've got a weidu.log generated on Windows machine which looks like this:

```
// ...
~BG1UB\SETUP-BG1UB.TP2~ #0 #11 // Scar and the Sashenstar's Daughter: v16.4
// ...
```

Here, path separator breaks the following code from mod installer: 

```
        let tp_file = install_path
            .split('/')
            .nth(1)
            .expect("Could find tp2 file")
            .to_string();
```

**Comment by dark0dave** [comment]
Sure I'll check on that.

**Comment by dark0dave** [comment]
This https://doc.rust-lang.org/std/path/constant.MAIN_SEPARATOR.html should fix that. Thank you for the issue!
