### ISSUE TITLE
New build does not work on windows

### ISSUE THREAD

**Issue by podcherklife** [dark0dave/mod_installer#22]
When running 2.2.0 on windows, mod installer produces `Could find tp2 file` error on perfectly valid files(even on empty ones).
Linux executable seems to work fine with the same files.

2.1.0 works fine though.

**Comment by dark0dave** [comment]
So the --skip-installed is weidu, can't really fix that from here.

**Comment by dark0dave** [comment]
Ah my bad, ok I have a fix.

**Comment by dark0dave** [comment]
@podcherklife I have fixed both your issues, please try again. Please open new issue if there any more bugs. 

Thank you again!

**Comment by dark0dave** [comment]
I'll create a new release as well.

**Comment by dark0dave** [comment]
```sh
mod_installer -s  --log-file
```
> 2023-11-11T18:39:17Z DEBUG mod_installer] Number of mods found: 107, Number of mods to be installed: 19

looks to be functioning properly now.
