### ISSUE TITLE
Handling user input-required mods

### ISSUE THREAD

**Issue by SarahG-579462** [dark0dave/mod_installer#81]
Some mods, notably romance cheats in cdtweaks and item-randomizer, require user input for many of their components. This doesn't seem supported at the moment. Any suggestions on how to fix this?

**Comment by dark0dave** [comment]
Hi @SarahG-579462, weidu gives us some tooling here, the question block in my code should deal with it.

Do you have the wiedu log and the error in question?

**Comment by SarahG-579462** [comment]
Hi dave, I couldn’t get a weidu log because it wasn’t outputting to the
terminal, just getting stuck in a loop. The mods it looped on were
item-randomizer, and if I remember correctly, EET_Tweaks.

Tweaks anthology had an issue where if you use the unattended install
feature (cdtweaks.txt), your code catches that it’s asking for input, but
it shouldn’t, cd-tweaks just outputs that automatically.

**Comment by dark0dave** [comment]
@SarahG-579462, so this isn't really compatable with cdtweaks.txt unattended install. But I'll take a look to see if I can make it work! I'll have a look at EET_Tweaks randomizer. 

Give me a little time and I'll see what I can do!

**Comment by dark0dave** [comment]
I had I look at EET_Tweaks I couldn't see anything particularly wrong. Item randomizer, I assume this:

````sh
Please enter the chance for items to randomly not be randomised as a integet number (e.g. 10 for 10%)
```
was the issue?

**Comment by SarahG-579462** [comment]
Indeed. 

For EET_Tweaks, it was for the xp cap mods I believe (custom cap). I might be misremembering though, my weidu list is over 1000 components now...

**Comment by dark0dave** [comment]
I have a fix give me a sec.

**Comment by dark0dave** [comment]
> Indeed.
> 
> For EET_Tweaks, it was for the xp cap mods I believe (custom cap). I might be misremembering though, my weidu list is over 1000 components now...

Living like me. Mines near 1000 too.

**Comment by dark0dave** [comment]
I'll cut a release for this in a bit
