### ISSUE TITLE
Output all logs to files

### ISSUE THREAD

**Issue by SarahG-579462** [dark0dave/mod_installer#84]
One of the disadvantages I found with this tool is that there is only ever the latest mod component in the log. Could this be changed to append to `setup-(modname).debug`? I imagine this could be done with `weidu --log (filename)` in your call, since if I remember right this appends by default.

**Comment by dark0dave** [comment]
Sure this is an easy one to add, I can add a flag.

**Comment by dark0dave** [comment]
I will add the flag log mode:

which will support:

```
  --log X       log output and details to X
  --autolog     log output and details to WSETUP.DEBUG
  --logapp      append to log instead of overwriting
  --log-extern  also log output from commands invoked by WeiDU
```

**Comment by dark0dave** [comment]
@SarahG-579462 you'll be able pass multiple settings:

example:

```sh
--weidu-log-mode log /somepath logapp log-extern
```
